### ISSUE TITLE
Dist. Version of Concrete v4

### ISSUE THREAD

**Issue by bacounts** [Elkfox/Concrete#105]
I am looking for a dist version of the latest Concrete theme. I would love to use this in a school project, and any help or an upload-ready version for Shopify would be amazing.

**Comment by cam** [comment]
@bacounts done! There's now a [pre-compiled zip available in the root folder](https://github.com/Elkfox/Concrete/raw/master/concrete-theme.zip) of the project :)

**Comment by bacounts** [comment]
Thank you so much! I am excited to use it!

**Comment by cam** [comment]
Git is getting confused between differing binaries for some reason. Possibly related to ignore patterns. The latest few commits seem to have overcome that issue, so the compiled zip of the file should now be ready to go.
