### ISSUE TITLE
SourcemappingUrl

### ISSUE THREAD

**Issue by austinhutchison** [Elkfox/Concrete#107]
Hi Concrete team,

First off - I've enjoyed exploring this project and I am only vaguely familiar with these types of build processes.  So apologies in advance for a naive issue.

Out of the box - I was able to build the project, and it generated the associated source maps and uploaded them to the Shopify asset folder. 

However, the required `//# sourceMappingURL=` is missing from the minified javascript files. 

Would it make sense for the generated javascript files to be `.js.liquid` files so you could include `//# sourceMappingURL={{ 'xxx.js.map' | asset_url }}`

I'm not sure how to adjust the build process to add this line, or whether that's the appropriate solution.

Thanks!

**Comment by cam** [comment]
Hey @austinhutchison Apologies for the slow reply here. We're a little overly busy so far in 2020. Thanks for the feedback!

Did you resolve this issue? I haven't seen the same error myself.
