### ISSUE TITLE
Addresses pagination not working with render, but only with old include

### ISSUE THREAD

**Issue by marioloncarek** [Elkfox/Concrete#108]
First of all thanks for great starter theme. Love it.

**Describe the bug**
Pagination snippet is not rendering with new `render` tag, but works if you call it with `include`

**To Reproduce**
1. Go to account addresses inside user account area
2. Add some addresses, enough to trigger the pagination render
4. Pagination is not rendering and .pagination element renders empty

**Expected behavior**
Pagination showing

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser : All
 - Version: Latest

**Additional context**
`{% include 'pagination' %}` fixes it, but since this is deprecated, i dont know if its good to use include anyomore

**Comment by cam** [comment]
@marioloncarek Thanks for the feedback! It is genuinely appreciated 👍

We'll be replacing all of the include tags with render tags very soon. I'll make sure to prioritise this. We should have a new version up in the next few days.

**Comment by marioloncarek** [comment]
Perfect man!  been looking for vanilla Slate replacement. If you need any help with repos im happy to contribute!

**Comment by cam** [comment]
Contributions are always welcome :)

Sorry for the slow action here. We're pretty run off our feet right now. But I assure you an update is on its way.

**Comment by marioloncarek** [comment]
dont even mention it, take your time :)
