### ISSUE TITLE
Theme settings need cleanup

### ISSUE THREAD

**Issue by cam** [Elkfox/Concrete#11]
The theme settings have reverted to an old version. We'll need to manually clean them up for the new methods.

**Comment by cam** [comment]
Theme info proposal;
```
 {
    "name": "theme_info",
    "theme_name": "Concrete",
    "theme_author": "Elkfox",
    "theme_version": "2.0.0",
    "theme_documentation_url": "https://elkfox.github.io/Concrete/",
    "theme_support_email": "help@elkfox.com"
  }
```

**Comment by georgebutter** [comment]
I'll add this bit in now.

**Comment by georgebutter** [comment]
Do we remove the color options? I feel like changing colours won't be used by most merchants. The settings should all be merchant focused really.

**Comment by cam** [comment]
Yeah I think so. There should be minimal colour config available in the base framework.
