### ISSUE TITLE
Popups need updating to latest

### ISSUE THREAD

**Issue by cam** [Elkfox/Concrete#16]
I'll update these myself soon 👍

**Comment by georgebutter** [comment]
I think they are already?

**Comment by cam** [comment]
They are mostly. But I had been working on some new functionality and efficiency that I need to roll in.

**Comment by cam** [comment]
Oh, I also need to set up the main project for the popup system.

**Comment by georgebutter** [comment]
https://github.com/Elkfox/Concrete-Popups

**Comment by cam** [comment]
Lovely 😄 ...let's roll this in to Concrete ✌🏼
