### ISSUE TITLE
Quantity elements should not be input field

### ISSUE THREAD

**Issue by georgebutter** [Elkfox/Concrete#18]
With input fields, we have to wrestle with the user agent styling of text and number inputs.

**Comment by cam** [comment]
Interesting idea! A fallback would be more difficult.

**Comment by georgebutter** [comment]
> A fallback would be more difficult

In what way?

**Comment by cam** [comment]
If it falls back to an input field, the users can still add quantities without requiring JS. Maybe that doesn't matter though, what were you thinking the replacement would be?

**Comment by georgebutter** [comment]
Good point, I mostly don't like it being a number field. User agent styling on some browsers has not been reset and you get the up and down buttons. But it also shouldn't really be a text field/editable.
Could use `noscript` as a fallback but that is ugly...

I don't want Cartfox to have to rely on an input field value either, on ajax templates it doesn't make much sense to be able to edit the number.
