### ISSUE TITLE
Duplicated logo settings

### ISSUE THREAD

**Issue by cam** [Elkfox/Concrete#20]
We currently have duplicated settings for logos. This needs a cleanup, as does the way we define meta images like opengraph, favicon and itemprop sources.

It looks like "favorites_pinned_svg" isn't defined yet either.

I think this should take the form of settings for both a bitmap and svg image to be applied dynamically per use.

**Comment by georgebutter** [comment]
This sounds good! Do you have a recommend structure for the fav images I know there are supposed to be lots of different dimensions.

**Comment by oscarstranger** [comment]
@ButsAndCats this is a good guide for Favicons: https://github.com/joshbuchea/HEAD

[As implemented in RC](https://github.com/Elkfox/Reinforced-Concrete/blob/master/snippets/meta-favorites.liquid)

**Comment by cam** [comment]
+1 ...that's literally my go to
