### ISSUE TITLE
JSON-LD schema markup

### ISSUE THREAD

**Issue by cam** [Elkfox/Concrete#25]
I think we should consider moving to JSON-LD for the offer (and other) schema markup. It's more easy to manage updates as the standards evolve. How it is set up right now it is too easy to break the structure, and updating is overly complex.

See https://developers.google.com/search/docs/data-types/products

Thoughts and feedback very welcome 🤓

**Comment by georgebutter** [comment]
Agreed 👍  

nice tidy snippet.

**Comment by oscarstranger** [comment]
See #78
