### ISSUE TITLE
collection-product.liquid data-product-tags will close itself, if a tag contains a double quote

### ISSUE THREAD

**Issue by jibinycricket** [Elkfox/Concrete#27]
In snippets/collection-product.liquid, the data attribute "data-product-tags", closes itself if one of the tags contains a double quote.

I'm also really not sure what this attribute is being used for at the moment, along with data-product-id and data-product-price

**Comment by cam** [comment]
Thanks @jmathew1991, I'll look into this. I'm about to do a round of overhauls.

The data product tags was used in a beta version for some rather fancy live filtering. I don't think we need it there for now. The live filtering will likely come back as an optional plugin later on.

**Comment by georgebutter** [comment]
Removed.
