### ISSUE TITLE
Focus: Can't close using the wrapper after clicking into the popup-content

### ISSUE THREAD

**Issue by jibinycricket** [Elkfox/Concrete#33]
After triggering the popup, it can be closed by clicking the wrapper. If you click on the "popup-content" div and then the wrapper, the wrapper no longer closes the popup.

[https://gfycat.com/OptimisticAmpleGibbon](https://gfycat.com/OptimisticAmpleGibbon)

**Comment by oscarstranger** [comment]
Thanks for raising this @jmathew1991, this issue has been fixed in the latest version of both Concrete and [Focus](https://github.com/Elkfox/Focus).
