### ISSUE TITLE
Missing Translations

### ISSUE THREAD

**Issue by jibinycricket** [Elkfox/Concrete#36]
Translations Missing for the following:

/templates/activate_account.liquid
`<h1>{{ 'account.activate.title' | t }}</h1>`

/snippets/popup-address.liquid
`<h4>{{ 'account.address.delete' | t }}</h4>`

**Comment by oscarstranger** [comment]
Also missing common.meta translations

```
"meta": {
  "page": "Page {{ page }}",
  "tags": "Tagged with {{ tags }}"
},
```
