### ISSUE TITLE
Checkout.liquid

### ISSUE THREAD

**Issue by georgebutter** [Elkfox/Concrete#56]
Include checkout liquid and scss by default

**Comment by georgebutter** [comment]
or a dummy template in the readme?

**Comment by oscarstranger** [comment]
Dummy template could be good, otherwise our own template in reinforced

**Comment by oscarstranger** [comment]
This can be generated inside the online theme editor by selecting a `new template > checkout` that file can then be copied to the repo on a project by project basis.
