### ISSUE TITLE
Giftcard page

### ISSUE THREAD

**Issue by georgebutter** [Elkfox/Concrete#69]
Styling and locales

**Comment by oscarstranger** [comment]
Rebuild from scratch

**Comment by georgebutter** [comment]
check out Jean Jail

**Comment by oscarstranger** [comment]
From @Cam 

> The gift card template needs testing and improving upon.
> 
> It would be good to include some custom fields on both the gift card product page and the gift card landing page itself...
> See: https://help.shopify.com/themes/liquid/objects/gift-card#gift_card-properties
> (and https://help.shopify.com/themes/liquid/objects/line_item#line_item-properties)
> 
> The templates to rework are:
> 
> ## templates/product.liquid
> 
> This template needs an if statement to identify if the product is a gift card, then show a custom layout to suit if it is. There should also be a new section created for gift card customisation.
> 
> Needs some sample line item info like "To name", "Custom message", etc.
> 
> ## layout/gift_card.liquid & templates/gift_card.liquid
> 
> These templates need testing and customisation. They are the landing pages for customers who click through from the gift card email to view the online version with value/spent and other details.
> 
> Needs some sample line item info like "To name", "Custom message", etc.

**Comment by oscarstranger** [comment]
### Gift card page verification & fix:
- MMC
- Verloop
- ABS
- Teach Me Fashion
- Emperor
- RW Wholesale
- Kerrin

**Comment by cam** [comment]
This won't be required with the new version.
