### ISSUE TITLE
Cart page controls arent working

### ISSUE THREAD

**Issue by jibinycricket** [Elkfox/Concrete#7]
Wasn't sure if you guys haven't gotten to it yet but the cart line item controls don't update the cart.

**Comment by georgebutter** [comment]
Awesome thanks for raising an issue! A lot of elements have recently been rebuilt so there may be a few bugs like this. Let us know if you find any others!

**Comment by georgebutter** [comment]
This has been patched now.

**Comment by georgebutter** [comment]
7739f64

**Comment by jibinycricket** [comment]
Thanks for the quick fix. +/- Now change quantity after pressing the update button. However the remove button still doesn't work.

Also is there a reason why there needs to be an update button on the cart page, instead of automatically updating as it does in the AJAX cart?

**Comment by ButsAndCats** [comment]
> Also is there a reason why there needs to be an update button on the cart page, instead of automatically updating as it does in the AJAX cart?
It can be turned into an ajax cart, but we didn't feel that this should be the default functionality of the framework.

I will take a look into the remove button on Monday!

**Comment by georgebutter** [comment]
> Also is there a reason why there needs to be an update button on the cart page, instead of automatically updating as it does in the AJAX cart?

It can be turned into an ajax cart, but we didn't feel that this should be the default functionality of the framework.

I will take a look into the remove button on Monday!

**Comment by georgebutter** [comment]
Okay, I've just fixed it actually.
