### ISSUE TITLE
Features for Concrete images js

### ISSUE THREAD

**Issue by cam** [Elkfox/Concrete#70]
I'd like to rebuild the default product image gallery for the upcoming Slate v1 version of Concrete.

Let's build on what you already created @ButsAndCats, but support basic touch interaction and a more elegant integration with Focus, in a specifically Shopify-esque way.

**Comment by cam** [comment]
For reference, though mostly already accommodated https://www.shopify.com/partners/blog/product-variants

**Comment by oscarstranger** [comment]
It'd be great to build in some lazy loading support in this too, as well as some methods for linking variants and images.

Also to consider would be how ratios build on this method too, so we can still utilise background image ratio blocks as easily as we can with Slick sliders #71

**Comment by cam** [comment]
This won't be required with the new version.
