### ISSUE TITLE
Wordpress Integration 

### ISSUE THREAD

**Issue by sandeep2244** [Elkfox/Concrete#72]
Hi
   This theme is too good, it has beautiful layout. It fits in our selection criteria but it is in Shopify. We want it to be integrated in Wordpress.
How can I get it?

**Comment by oscarstranger** [comment]
Hi @sandeep2244, 

Thanks for the feedback, we love this theme too. Unfortunately, we have no plans to migrate this theme to WordPress ourselves, as we have no use for the platform. In saying that, if you were to replace the [Liquid](https://github.com/Shopify/liquid) tags with PHP and compile the SCSS, you'd have a working store that you could port to other platforms, like WordPress, if needed.

It's also worth noting that several of the libraries used in this framework are also some of our standalone projects that are readily available to use on any site, such as [Focus](https://elkfox.github.io/Focus/) and [Grid50](https://github.com/Elkfox/grid50).

If you do build a store on Shopify, we will also be releasing a new version of our cart framework called Cartfox in the coming months, so stay tuned.
