### ISSUE TITLE
Cocrete v4

### ISSUE THREAD

**Issue by soulzzprajapati** [Elkfox/Concrete#82]
Out of the box, there is an issue with the cart http://prntscr.com/p3m1kg
what's the best way to fix this? I can't seem to find any documentations related to v4.

**Comment by cam** [comment]
@soulzzprajapati that error is coming from the demo elements. We'll have some documentation up soon. v4 is not quite launched yet 😁

**Comment by soulzzprajapati** [comment]
That's alright. Excited for this version to be ready.

**Comment by cam** [comment]
Me too! 👌
