### ISSUE TITLE
Errors when uploading zip to Shopify

### ISSUE THREAD

**Issue by ianjwhitmore** [Elkfox/Concrete#84]
I have downloaded the Zip files from https://elkfox.github.io/Concrete/#getting-started and uploaded that to Shopify but I immediately get Liquid errors and most, if not all of the styles, do not load.

"Liquid error: Could not find asset snippets/style-tags.liquid Liquid error: Could not find asset snippets/script-tags.liquid"

I am not using Slate but my understanding is that Concrete should still work with a simple upload?

**Comment by cam** [comment]
I think you might be looking for the v2 release, which can be found in the /dist folder in this release:  https://github.com/Elkfox/Concrete/releases/tag/v.2.0

The new version doesn't include a compiled version for uploading via the Shopify UI (as yet).

The docs are currently being rewritten. Sorry for the confusion!
