### ISSUE TITLE
Password Page: "Have a password?" link isn't triggering the "#PasswordPagePopup"

### ISSUE THREAD

**Issue by jibinycricket** [Elkfox/Concrete#9]

**Comment by cam** [comment]
@jmathew1991 Thanks of logging this. That makes sense considering the substantial diversion in the latest version. We'll create a fix.

**Comment by georgebutter** [comment]
Thanks for raising this issue. It was using an older version of concrete popups.

@jmathew1991 Has been fixed now. You can replace the link with the following:
`<a href="" data-trigger="trigger" data-target="#PasswordPagePopup">{{ 'password_page.password_link' | t }}</a>`

There is some documentation about the popups here: https://elkfox.github.io/Concrete/#concrete-popups

We would be glad to take a PR if you find any more of these!

0645229
